# Generated by Django 5.2.5 on 2025-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CONFIRMED', 'Booking Confirmed'), ('CANCELLED', 'Booking Cancelled'), ('COMPLETED', 'Booking Completed')], max_length=20),
        ),
    ]
